# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/trailblazer-context/all/trailblazer-context.rbi
#
# trailblazer-context-0.5.0

module Trailblazer
  def self.Context(wrapped_options, mutable_options = nil, context_options = nil); end
end
module Trailblazer::Context
  def build(wrapped_options, mutable_options, container_class:, **context_options); end
  def for_circuit(wrapped_options, mutable_options, arg2, **arg3); end
  def self.build(wrapped_options, mutable_options, container_class:, **context_options); end
  def self.for_circuit(wrapped_options, mutable_options, arg2, **arg3); end
end
module Trailblazer::Context::Store
end
